### ISSUE TITLE
Adicionar comando de profile

### ISSUE THREAD

**Issue by KingTimer12** [NovelBrasil/nebi#4]
# Sistema de Profile

## Sobre
> Adicionar todo o sistema de profile dentro do bot. O foco aqui é apenas implementar, a economia ficará para outro Issue.

## TODO List
- [x] Comando `/profile card`
- [x] Comando `/profile criar`
- [x] Aplicar o sistema de medalhas
- [x] Comando `/profile medalhas`
   - [x] Sistema de ver suas medalhas: ativas, desativadas e bloqueadas;
   - [x] Sistema de alterar: ativar e desativar;
- [x] Comando `/profile carteira`
   - [x] Ver o quanto você tem na forma bruta. Sem formatação;
- [x] Comando `/profile bandeira`
   - [x] Sistema de ver bandeiras disponíveis;
   - [x] Sistema de alterar bandeira;
- [x] Comando `/profile fundo`
